### ISSUE TITLE
inline crashes with AttributeError

### ISSUE THREAD

**Issue by Nudin** [python-rope/rope#304] opened 2020-08-15 15:06 UTC
When trying the inline feature with this example from the Featurelist with ropevim, I get an error with the stacktrace below.
```
class C(object):

    var = 1

    def f(self, p):
        result = self.var + pn
        return result


c = C()
x = c.f(1)
```

```
Error involking "function RopeInline[1]..provider#python3#Call":                                                       
Zeile   18:                                                                                                                      
Error invoking 'python_execute' on channel 3 (python3-script-host):                                                              
Traceback (most recent call last):                                                                                               
  File "<string>", line 1, in <module>                                                                                           
  File "/usr/lib/python3.8/site-packages/ropemode/decorators.py", line 54, in newfunc                                            
    return func(*args, **kwds)                                                                                                   
  File "/usr/lib/python3.8/site-packages/ropemode/interface.py", line 52, in do_refactor                                         
    refactoring(self, self.env).show(initial_asking=initial_asking)                                                              
  File "/usr/lib/python3.8/site-packages/ropemode/refactor.py", line 32, in show                                                 
    self._create_refactoring()                                                                                                   
  File "/usr/lib/python3.8/site-packages/ropemode/refactor.py", line 264, in _create_refactoring                                 
    self.inliner = rope.refactor.inline.create_inline(                                                                           
  File "/usr/lib/python3.8/site-packages/rope/refactor/inline.py", line 52, in create_inline                                     
    return InlineVariable(project, resource, offset)                                                                             
  File "/usr/lib/python3.8/site-packages/rope/refactor/inline.py", line 217, in __init__                                         
    self._init_imports()                                                                                                         
  File "/usr/lib/python3.8/site-packages/rope/refactor/inline.py", line 263, in _init_imports                                    
    self.imported, self.imports = move.moving_code_with_imports(                                                                 
  File "/usr/lib/python3.8/site-packages/rope/refactor/move.py", line 711, in moving_code_with_imports                           
    source = _add_imports_to_module(import_tools, pymodule, imports)                                                             
  File "/usr/lib/python3.8/site-packages/rope/refactor/move.py", line 682, in _add_imports_to_module                             
    return module_with_imports.get_changed_source()                                                                              
  File "/usr/lib/python3.8/site-packages/rope/refactor/importutils/module_imports.py", line 69, in get_changed_source            
    after_removing = self._remove_imports(self.imports)                                                                          
  File "/usr/lib/python3.8/site-packages/rope/refactor/importutils/module_imports.py", line 105, in _remove_imports              
    first_import_line = self._first_import_line()                                                                                
  File "/usr/lib/python3.8/site-packages/rope/refactor/importutils/module_imports.py", line 240, in _first_import_line           
    if self.pymodule.get_doc() is not None:                                                                                      
  File "/usr/lib/python3.8/site-packages/rope/base/pyobjects.py", line 227, in get_doc                                           
    return _decode_data(docstring, coding)                                                                                       
  File "/usr/lib/python3.8/site-packages/rope/base/fscommands.py", line 220, in _decode_data                                     
    encoding = read_str_coding(data)                                                                                             
  File "/usr/lib/python3.8/site-packages/rope/base/fscommands.py", line 258, in read_str_coding                                  
    first = source.index(newline) + 1                                                                                            
AttributeError: 'int' object has no attribute 'index'
```

**Comment by lieryan** [comment] 2021-09-07 20:22
Closing. Cannot reproduce using latest rope.

rope==0.19.0 ropemode==0.5 ropevim==0.8.1

**Closed by lieryan** 2021-09-07 20:22 UTC
