### ISSUE TITLE
proposal: release automation via git tags

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [python-rope/rope#198] opened 2017-01-24 16:45 UTC
**shameless self plug**

im the author of setuptools_scm and using it in a number of my project in combination with travis deplys and git tags in order to push releases to pypi easily and effortlessly

while it doesn't solve surrounding issues like change-log management or announcements,
it can provide a straightforward pipeline of git tag to release on a painless basis

if the maintainers like the idea i can propose the changes needed for that automation via a few pull request

**Comment by soupytwist** [comment] 2017-01-24 16:53
I would be open to it. Currently we don't have much of a release plan (though the project hasn't been under active development for a while) but we do need to get on a regular schedule. Improving the release tooling would be a good step forward.

**Comment by mcepl** [comment] 2019-02-11 11:30
Well, we try to have python-rope with as few dependencies outside of stdlib as possible. And (putting on my openSUSE Python maintainer hat) ``setuptools_scm`` has rather unpleasant dependency tree.

**Comment by RonnyPfannschmidt** [comment] 2019-02-11 12:02
@mcepl care to elaborate - im open to sorting those details out

**Comment by mcepl** [comment] 2019-02-11 12:36
It is completely off-topic in this bug. openSUSE is very much devoted to the idea of https://reproducible-builds.org, which in the end means that we cannot have any BuildRequirements cycles and thus large dependency trees are problem. I spent quite some time making sure that Python 3.7 builds in our system and I spent a lot of time with resolving such issues (many packages have some line in ``requirements.txt`` just from laziness to remove it or “perhaps you may need it for debugging” or something). ``setuptools_scm`` is sane in this respect, but it is quite deep (or high, close to the root, which is ``python-base`` package), so any BR may turn to be quite a problem, and in the end the value it brings is so little, that we ended up with patching it as a dependency couple of times (and writing the version number with ``sed(1)``, or something).

Python-rope is in this respect not that big problem, because it is rather shallow dependency (it is used only by few editor plugins and IDEs).

**Comment by lieryan** [comment] 2022-11-30 11:52
Closing. As we have no immediate plan to use setuptools-scm.

**Closed by lieryan** 2022-11-30 11:52 UTC
