### ISSUE TITLE
RopeExtractVariable doesn't work for me

### ISSUE THREAD

**Issue by mcepl** [python-rope/rope#216] opened 2017-10-08 17:20 UTC
Using rope (0.10.7, ropemode 0.4, python 2.7) I get this situation (sorry, for filing a bug with screenshot, but I think it is the easiest way how to capture the situation here):
![screenshot from 2017-10-06 13-12-20](https://user-images.githubusercontent.com/198999/31319074-47713722-ac5d-11e7-89c4-e9d09b03c490.png)
It seems to me that my selection pretty well covers perfect Python statement. What's wrong?

**Comment by Huge** [comment] 2020-06-06 10:08
Maybe it took the `)` which made it choke?

**Comment by lieryan** [comment] 2021-09-06 18:47
Closing. This is most likely caused by https://github.com/python-rope/ropevim/pull/89.

**Closed by lieryan** 2021-09-06 18:47 UTC
Labels: question
