### ISSUE TITLE
Unknown node type <Nonlocal>; please report! RuntimeWarning

### ISSUE THREAD

**Issue by julian-goettingen** [python-rope/rope#689] opened 2023-05-30 07:31 UTC
I am getting the error in the title. Coming from refactor/patchedast.py:84
Unfortunately I do not know what exact code causes this (though I guess it must have to do with the nonlocal-keyword)
Sorry I do not have a short example, but when the message tells me to report the bug, the least I can do is report it.
This problem is not causing my script to fail, probably because my refactor has nothing to do with the nonlocal-keyword.

Python3.7.9
rope1.8.0
no IDE (I am using rope as a library in my script)

**Comment by julian-goettingen** [comment] 2023-05-30 07:32
very cool library by the way, it saves me a ton of work.

**Comment by lieryan** [comment] 2023-05-30 12:37
Hi @julian-goettingen, thank you for taking the time to write this issue. I know exactly what this issue is, we just had not implemented `nonlocal` keyword. This is essentially duplicate of #624, so I'll close this one.

**Closed by lieryan** 2023-05-30 12:37 UTC
Labels: bug, duplicate
