### ISSUE TITLE
simple refactoring within class fails

### ISSUE THREAD

**Issue by mdcaio** [python-rope/rope#302] opened 2020-06-29 13:25 UTC
I have a problem when refactoring within a class. Below a minimal working example.

Within VSCode, in the file `test_rope.py`, I'm trying to refactor this:
```
class Test():
    def __init__(self, a=0, b=None):
        self.a = a
        self.b = b if b is not None else self.a**2
```
into this:
```
class Test():
    def __init__(self, a=0, b=None):
        self.a = a
        self.b = self.__set_b(b)
    def __set_b(self, b):
        return b if b is not None else self.a**2
```
however, I get the error `Cannot perform refactoring using selected element(s). Refactor failed. Attribute rope_test not found ...`

Is this an expected behaviour? And, if yes, why?

**SIDE NOTE**
Notice that if the class was instead this (**no self.a but just a in the definition of self.b**)
```
class Test():
    def __init__(self, a=0, b=None):
        self.a = a
        self.b = b if b is not None else self.a**2
```
the refactoring is performed with the following result:
```
class Test():
    def __init__(self, a=0, b=None):
        self.a = a
        self.b = self.__set_b(a, b)
    def __set_b(self, a, b):
        return b if b is not None else a**2
```
which is rather good, although I'd expect this instead
```
class Test():
    def __init__(self, a=0, b=None):
        self.a = a
        self.b = Test.__set_b(a, b)

    @staticmethod
    def __set_b(a, b):
        return b if b is not None else a**2
```

**python 3.7.6, rope 0.16.0 and 0.17.0**

**Comment by climbus** [comment] 2021-09-06 20:10
Example 1: I can't reproduce: https://github.com/climbus/rope/blob/issue_302/ropetest/refactor/extracttest.py#L1301
I've created a test for it, but works fine.

**Comment by lieryan** [comment] 2021-09-07 18:02
@climbus thanks for testing this out, yes, this seems to have already been fixed in latest rope.

**Closed by lieryan** 2021-09-07 18:02 UTC
Labels: extract-refactor

**Comment by climbus** [comment] 2021-09-07 18:43
I'm wondering on the second example. If I have good understanding, static method is extracted if code is inside static method. 
Maybe rope should extract to static method if there are no reference to self? On the other hand, extracting to static method by default may be the wrong idea.

**Comment by lieryan** [comment] 2021-09-07 20:11
Yeah, I don't think automatically extracting into a staticmethod just because the section of code doesn't reference `self` would be a good default.

The way I see it, changing the method type (i.e. regular/staticmethod/classmethod) should be something that the user explicitly decides to do, rather than rope trying to guess based on usage of `self`.

`ExtractMethod.get_changes()` currently doesn't seem to have an option to force extracting a block of code from a regular method into a `staticmethod`/`classmethod`, which seems to be a missing feature.

**Comment by lieryan** [comment] 2021-09-07 21:47
> Yeah, I don't think automatically extracting into a staticmethod just because the section of code doesn't reference self would be a good default.

Having said that, if someone wants to make a PR to make it an option that can be configured in `.ropeproject/config.py` to have rope add `staticmethod` automatically if the extracted code section doesn't reference `self`, I'd be open to it.
