### ISSUE TITLE
MismatchedTokenError when matching keyword splats

### ISSUE THREAD

**Issue by perimosocordiae** [python-rope/rope#98] opened 2014-11-11 22:03 UTC
As far as I can tell, this only occurs when the code has a keyword splat after a regular splat and an explicit keyword argument in a function call. For example, when running a refactor on the file:

```
bar(*a, b=5, **c)
```

rope produces the error:

```
rope.refactor.patchedast.MismatchedTokenError: Token <a> at (1, 14) cannot be matched
```

which corresponds to the location of the `**` keyword splat

If you remove the explicit keyword and run it on `bar(*a, **c)`, everything is fine. If you remove the first splat (`bar(a, b=5, **c)`), it also works fine.

Environment:
- Ubuntu 14.10
- Python 2.7.8
- master branch of Rope (installed via pip from github)

**Comment by lieryan** [comment] 2021-09-07 18:54
Closing. Cannot reproduce in latest rope, if you believe this is still an issue, please provide more information to help reproduce, such as what kind of refactoring you're trying to do or what steps you took.

**Closed by lieryan** 2021-09-07 18:54 UTC
Labels: bug, extract-refactor
