### ISSUE TITLE
python2 test failures on Fedora

### ISSUE THREAD

**Issue by nonamedotc** [python-rope/rope#220] opened 2017-10-21 14:32 UTC
Possibly related to #211 .

I am seeing test failures when I try to build rope-0.10.7 on Fedora python2. I have not tried with python 3.

```
======================================================================
FAIL: test_time_in_std_mods (ropetest.builtinstest.BuiltinModulesTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/rope-0.10.7/ropetest/builtinstest.py", line 503, in test_time_in_std_mods
    self.assertTrue('time' in rope.base.stdmods.standard_modules())
AssertionError: False is not true
======================================================================
FAIL: test_sorting_imports_and_standard_modules2 (ropetest.refactor.importutilstest.ImportUtilsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/rope-0.10.7/ropetest/refactor/importutilstest.py", line 814, in test_sorting_imports_and_standard_modules2
    self.import_tools.sort_imports(pymod))
AssertionError: 'import sys\nimport time\n' != u'import sys\n\nimport time\n'
----------------------------------------------------------------------
```

**Comment by soupytwist** [comment] 2017-10-23 23:59
Ah, it does indeed look related. I'll revisit this...

**Comment by soupytwist** [comment] 2017-11-08 00:56
Closing as duplicate of #211, will push a fix there.

**Closed by soupytwist** 2017-11-08 00:56 UTC
Labels: bug
