### ISSUE TITLE
Odd issue with rename.py

### ISSUE THREAD

**Issue by benstaniford** [python-rope/rope#298] opened 2020-05-18 21:24 UTC
Hi there,

I'm not sure if this is quite the right place to ask this question (Because I'm not 100% which component is at fault) but I'm having the strangest stack trace from rope when trying to rename a variable.  Rope got installed by the vim plugin coc.nvim which provides language server capability for many languages including python.  

What's weird is that the stack trace seems to show that rope has discovered python files completely outside of my path and inside a VM on my machine which isn't even on the same OS (Linux rather than Windows).  It's erroring because those python files are in 2.7 format where the python on my machine is 3.8.

The stack trace looks like this:

[coc.nvim] Refactor failed. Syntax error in file <AppData/Local/Packages/CanonicalGroupLimited.Ubuntu18.04onWindows_79rh
kp1fndgsc/LocalState/rootfs/usr/lib/python2.7/lib2to3/pgen2/pgen.py> line <206>: Missing parentheses in call to 'print'.
 Did you mean print("Dump of NFA for", name)?
[
<FrameSummary file refactor.py, line 294 in watch>,
<FrameSummary file refactor.py, line 274 in _process_request>, 
<FrameSummary file refactor.py, line 206 in _rename>, 
<FrameSummary file refactor.py, line 117 in refactor>, 
<FrameSummary file refactor.py, line 139 in onRefactor>, 
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\refactor\rename.py, line 97 in get_changes>, 
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\refactor\rename.py, line 195 in rename_in_module>, 
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\refactor\occurrences.py, line 76 in find_occurrences>, 
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\base\utils\__init__.py, line 12 in _wrapper>, 
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\refactor\occurrences.py, line 392 in source_code>, 
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\base\utils\__init__.py, line 12 in _wrapper>, 
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\refactor\occurrences.py, line 412 in pymodule>, 
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\base\project.py, line 116 in get_pymodule>, 
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\base\pycore.py, line 142in resource_to_pyobject>, 
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\base\pycore.py, line 254 in get_pymodule>, 
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\base\pyobjectsdef.py, line 162 in __init__>, 
<FrameSummary file C:\Users\Ben\AppData\Roaming\Python\Python38\site-packages\rope\base\pyobjectsdef.py, line 191 in _init_source>]

So what's going on?  It's almost as though something was missing, and a filesystem search was started for the .py file.

**Comment by soupytwist** [comment] 2020-05-19 00:20
I think this question might be more related to [ropevim](https://github.com/python-rope/ropevim)... not sure though. @mcepl ?

**Comment by mcepl** [comment] 2020-05-19 10:09
No idea. Just a question, you use Linux vim under WSL or native Windows build of vim?

**Comment by benstaniford** [comment] 2020-05-19 12:32
@mcepl I use both, in that stack trace what you see is a native win32 vim, calling the native win32 python 3.8, which has somehow found the underlying filesystem belonging to WSL and found a 2.7 version of the python libraries in there.  These worlds should be completely separate since there's no configuration that links them.  The filesystem just happens to be accessible from the host OS.

**Comment by benstaniford** [comment] 2020-05-19 12:40
@mcepl 

Actually, now I look again, one suspicious thing I see is in the log file belonging to the CoC vim plugin.

2020-05-18T22:50:08.329 INFO (pid:6610) [extension-coc-python] - Python Extension: Create file systemwatcher with pattern */python
2020-05-18T22:50:08.333 INFO (pid:6610) [extension-coc-python] - Python Extension: Create file systemwatcher with pattern */*/python

I haven't looked at the source code, but I wonder if this is searching for python folders and adding them to the python runtime path or some such..  I assume that's possible, I'm not much of a Python person.

**Comment by mcepl** [comment] 2020-05-19 15:23
1. I am a Linux guy, I don’t have any Windows computer around, so it is hard to help here.

2. I don’t think I know about anybody who would test rope seriously in that crazy mixed two environment system as Windows with WSL.

3. With coc over it, I really don’t know where the problem could start.

For all these reasons, closing this without prejudice. If anybody finds where the problem is or sends a patch, I am willing to revisit this, but for now I cannot promise anything.

**Closed by mcepl** 2020-05-19 15:23 UTC

**Comment by benstaniford** [comment] 2020-05-19 18:20
@mcepl - I don’t think I know about anybody who would test rope seriously in that crazy mixed two environment system as Windows with WSL.

Well, I said I use them both, I didn't say I use them both simultaneously or mix them in any way.  The WSL system operates more or less like an entirely self contained Linux system.  It just happens to have some files visible from its host OS.  It's just Ubuntu 18.04 essentially.

> For all these reasons, closing this without prejudice. If anybody finds where the problem is or sends a patch, I am willing to revisit this, but for now I cannot promise anything

Yeh, that's fair enough.  I'll do some digging into whether coc is altering the Python runtime path in some way.

**Comment by mcepl** [comment] 2020-05-19 22:29
> The WSL system operates more or less like an entirely self contained Linux system. It just happens to have some files visible from its host OS.

Do you understand that these two sentences are mutually contradictory?

**Comment by benstaniford** [comment] 2020-05-20 13:33
> Do you understand that these two sentences are mutually contradictory?

The part you seem to have missed is "more or less".  A host operating system which has a filesystem link to a guest operating system could hardly be considered to be "crazy mixed two environment system as Windows with WSL".  

However, this is starting to get a little silly/petty/pedantic.  I'm grateful for your original help, and the CoC guys quickly spotted what the issue was.  Let's leave it.
